apiVersion: v1
kind: Secret
metadata:
  name: {{ template "my-flask-app.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.myappRootUsername | b64enc | quote }}
  password: {{ .Values.myappRootPassword | b64enc | quote }}