apiVersion: v1
kind: Service
metadata:
  name: {{ template "my-flask-app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "my-flask-app.name" . }}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "my-flask-app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "my-flask-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
          - name: db_username
            valueFrom:
              secretKeyRef:
                name: {{ template "my-flask-app.name" . }}
                key: username
          - name: db_password
            valueFrom:
              secretKeyRef:
                name: {{ template "my-flask-app.name" . }}
                key: password