apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mysql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:
    path: "/data/db"